import { SpriteProps } from './@core/Sprite';

const spriteData: { [index: string]: SpriteProps } = {
    ui: {
        src: './assets/ui.png',
        sheet: {
            'self-select': [
                [4, 0],
                [5, 0],
            ],
            select: [[4, 0]],
            dot: [[1, 0]],
            solid: [[0, 1]],
        },
    },
    player: {
        src: './assets/NectarineGirl/Nectarine-Tilesheet.png',
        frameWidth: 40,
        frameHeight: 40,
        frameTime: 150,
        sheet: {
            idleDown: [
                [0, 11],
                [1, 11],
                [2, 11],
                [3, 11],
            ],
            idleUp: [
                [0, 8],
                [1, 8],
                [2, 8],
                [3, 8],
            ],
            idleLeft: [
                [0, 10],
                [1, 10],
                [2, 10],
                [3, 10],
            ],
            idleRight: [
                [0, 9],
                [1, 9],
                [2, 9],
                [3, 9],
            ],
            walkUp: [
                [0, 4],
                [1, 4],
                [2, 4],
                [3, 4],
                [4, 4],
                [5, 4],
            ],
            walkDown: [
                [0, 7],
                [1, 7],
                [2, 7],
                [3, 7],
                [4, 7],
                [5, 7],
            ],
            walkLeft: [
                [0, 6],
                [1, 6],
                [2, 6],
                [3, 6],
                [4, 6],
                [5, 6],
            ],
            walkRight: [
                [0, 5],
                [1, 5],
                [2, 5],
                [3, 5],
                [4, 5],
                [5, 5],
            ],
        },
    },
    objects: {
        src: './assets/Room/tileSheet.png',
        frameWidth: 32,
        frameHeight: 32,
        sheet: {
            floor: [[3, 0]],
            ULCorner1: [[0, 0]],
            ULCorner2: [[5, 0]],
            URCorner1: [[2, 0]],
            URCorner2: [[7, 0]],
            LRCorner: [[8, 0]],
            LLCorner: [[4, 0]],
            wall1: [[1, 0]],
            wall2: [[6, 0]],
            doorLeft: [[0, 5]],
            doorCenter: [[1, 5]],
            doorRight: [[2, 5]],
            lights1: [[4, 7]],
            lights2: [[5, 7]],
            lights3: [[6, 7]],
            lights4: [[4, 6]],
            lights5: [[5, 6]],
            lights6: [[6, 6]],
            bed1: [[4, 5]],
            bed2: [[5, 5]],
            bed3: [[6, 5]],
            bed4: [[4, 4]],
            bed5: [[5, 4]],
            bed6: [[6, 4]],
            bed7: [[3, 5]],
            n1: [[4, 3]],
            n2: [[5, 3]],
            n3: [[6, 3]],
            n4: [[4, 2]],
            n5: [[5, 2]],
            n6: [[6, 2]],
            n7: [[4, 1]],
            n8: [[5, 1]],
            n9: [[6, 1]],
            coffee1: [[7, 2]],
            coffee2: [[7, 1]],
            couch1: [[9, 7]],
            couch2: [[10, 7]],
            couch3: [[9, 6]],
            couch4: [[10, 6]],
            couch5: [[9, 5]],
            couch6: [[10, 5]],
            couch7: [[9, 4]],
            couch8: [[10, 4]],
            tv1: [[9, 3]],
            tv2: [[10, 3]],
            tv3: [[9, 2]],
            tv4: [[10, 2]],
            boxes1: [[7, 4]],
            boxes2: [[8, 4]],
            boxes3: [[7, 3]],
            boxes4: [[8, 3]],
            plant1: [[0, 7]],
            plant2: [[0, 6]],
            piano1: [[1, 7]],
            piano2: [[2, 7]],
            piano3: [[3, 7]],
            piano4: [[1, 6]],
            piano5: [[2, 6]],
            piano6: [[3, 6]],
            record1: [[0, 3]],
            record2: [[1, 3]],
            record3: [[0, 2]],
            record4: [[1, 2]],
            record5: [[2, 2]],
            record6: [[0, 1]],
            record7: [[1, 1]],
            record8: [[2, 1]],
            dogBed: [[9, 1]],
            dogFood: [[0, 4]],
            painting: [[10, 1]],
            window1: [[2, 4]],
            window2: [[3, 4]],
            window3: [[2, 3]],
            window4: [[3, 3]],
            mirror1: [[3, 2]],
            mirror2: [[3, 1]],
            dresser1: [[7, 7]],
            dresser2: [[8, 7]],
            dresser3: [[7, 6]],
            dresser4: [[8, 6]],
            dresser5: [[7, 5]],
            dresser6: [[8, 5]],
            chair: [[1, 4]],
            'workstation-1': [[0, 1]],
            'workstation-2': [[1, 1]],
            'coffee-machine': [[2, 1]],
            'coffee-machine-empty': [[3, 1]],
            pizza: [[4, 1]],
            plant: [[0, 2]],
            'zombie-plant-1': [[1, 2]],
            'zombie-plant-2': [[2, 2]],
        },
    },
    footstep: {
        src: './assets/footstep.png',
        sheet: {
            default: [
                [0, 0],
                [2, 0],
            ],
        },
        opacity: 0.75,
        frameTime: 150,
    },
};

export default spriteData;
